In [118]:
import numpy as np
import math
import numpy.matlib 
from numpy.linalg import inv
array=np.zeros((2,4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [119]:
array=np.ones((1,4))
print(array)

[[1. 1. 1. 1.]]


In [120]:
np.eye(2,dtype=int,k=3)

array([[0, 0],
       [0, 0]])

In [121]:
np.random.randn(3,2)

array([[ 1.24077492, -0.89271693],
       [-1.53447875,  0.22160022],
       [ 0.00423834, -0.46097276]])

In [122]:
np.matrix(25)*3

matrix([[75]])

In [123]:
math.sin(90)

0.8939966636005579

In [124]:
math.cos(45)

0.5253219888177297

In [125]:
math.sqrt(49)


7.0

In [126]:
x=np.random.randn(2,2)
print(x)
y=np.random.randn(2,2)
print(y)
np.dot(x,y)

[[ 1.12216835  0.0189497 ]
 [-0.82872992  0.3033478 ]]
[[ 1.74611792  1.36109004]
 [-1.59460935  0.39026061]]


array([[ 1.92922089,  1.53476749],
       [-1.9307814 , -1.00959134]])

In [127]:
np.transpose(x)

array([[ 1.12216835, -0.82872992],
       [ 0.0189497 ,  0.3033478 ]])

In [128]:
np.multiply(5,5)

25

In [129]:
x1=np.arange(20).reshape((4,5))
print(x1,"\n")
x2=np.arange(5)
print(x2)
np.multiply(x1,x2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[0 1 2 3 4]


array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76]])

In [130]:
x3=[[1,2],
    [3,4]]
x4=[1,2]
np.matmul(x3,x4)

array([ 5, 11])

In [131]:
a=np.arange(0,8,1).reshape(2,4)
print(a,"\n")
b=np.arange(4)
print(b)
np.add(a,b)

[[0 1 2 3]
 [4 5 6 7]] 

[0 1 2 3]


array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10]])

In [132]:
a=np.arange(0,8,1).reshape(2,4)
print(a,"\n")
b=np.arange(4)
print(b)
np.subtract(a,b)

[[0 1 2 3]
 [4 5 6 7]] 

[0 1 2 3]


array([[0, 0, 0, 0],
       [4, 4, 4, 4]])

In [133]:
a=np.arange(0,8,1).reshape(2,4)
print(a,"\n")
b=np.arange(4)
print(b)
np.divide(a,b)

[[0 1 2 3]
 [4 5 6 7]] 

[0 1 2 3]


C:\Users\RFAT~1\AppData\Local\Temp/ipykernel_5912/268672645.py:5: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(a,b)
C:\Users\RFAT~1\AppData\Local\Temp/ipykernel_5912/268672645.py:5: RuntimeWarning: invalid value encountered in true_divide
  np.divide(a,b)


array([[       nan, 1.        , 1.        , 1.        ],
       [       inf, 5.        , 3.        , 2.33333333]])

In [134]:
np.shape([[3,4,6,7,1]])

(1, 5)

In [136]:
a = [[[1., 2.], [3., 4.]],
     [[1, 3], [3, 5]]]
inv(a)

array([[[-2.  ,  1.  ],
        [ 1.5 , -0.5 ]],

       [[-1.25,  0.75],
        [ 0.75, -0.25]]])

In [137]:
print(5+5)
print(5-4)
print(6/3)
print(9*2)
print(9//5)
print(3**3)
print(9%5)

10
1
2.0
18
1
27
4


In [1]:
x=int(input("Please enter your age:"))

if x>=18 and x<=30:
    print("you can take it")
else:
    print("you can't")
    

Please enter your age:15
you can't


In [8]:
def low(a,b,c):
    lowerWords=[]
    if a.islower()==True:
        lowerWords.append(a)
    if b.islower()==True:
        lowerWords.append(b)
    if c.islower()==True:
        lowerWords.append(c)
    return lowerWords

low("hello","Selam","nasıl")

['hello', 'nasıl']

In [14]:
a=[]
b=[]
for i in range(0,3):
    for j in range(0,3):
        a.append(j)
    b.append(a)
    a=[]
for i in b:
    print(" ".join(str(i)))

[ 0 ,   1 ,   2 ]
[ 0 ,   1 ,   2 ]
[ 0 ,   1 ,   2 ]
